version: '3'

services:
    db:
        build:
            context: .
            dockerfile: mysql/Dockerfile
        environment:
            MYSQL_DATABASE: api-laravel
            MYSQL_ROOT_PASSWORD: 123456!@
            TZ: America/Sao_Paulo
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        volumes:
            - ./db_data:/var/lib/mysql
        ports:
            - 3306:3306
volumes:
    db_data: